// Fallback wildcard for .clj imports whose specific foo.clj.d.ts has not yet
// been generated by the Vite plugin. Once vite dev or vite build runs,
// the plugin emits a per-file foo.clj.d.ts (via allowArbitraryExtensions)
// and TypeScript uses that instead of this wildcard.
declare module '*.clj' {
  const _exports: Record<string, unknown>
  export default _exports
}
