#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = resolve(__dirname, '..')

const packageJsonPath = resolve(rootDir, 'package.json')
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
const version = packageJson.version

const outputPath = resolve(rootDir, 'src/bin/version.ts')
const content = `// This file is auto-generated by scripts/gen-version.mjs
// Do not edit manually - changes will be overwritten

export const VERSION = '${version}'
`

writeFileSync(outputPath, content, 'utf8')
console.log(`Generated version.ts with version ${version}`)
