/**
 * Integration tests for the clojure.test → vitest failure bridge.
 *
 * These tests exercise the ACTUAL session execution — not just code generation
 * string-matching. They verify that:
 *
 *   - Failing `is` assertions inside both sync and async deftests are captured
 *     in the `__vt_failures` atom (so the generated test wrapper can throw).
 *   - Multiple failures from a single deftest are all captured.
 *   - Uncaught `throw` forms propagate as rejected promises and make
 *     `evaluateAsync` throw (so vitest marks the test as errored, not just failed).
 *   - Passing assertions leave `__vt_failures` empty.
 *
 * The session setup here mirrors exactly what `generateTestModuleCode` emits,
 * so regressions in either the codegen or the evaluator are caught here.
 */

import { describe, it, expect } from 'vitest'
import { createSession, cljToJs } from '../../core/index'
import type { Session } from '../../core/index'

// ---------------------------------------------------------------------------
// Helper — mirrors the session setup generated by generateTestModuleCode
// ---------------------------------------------------------------------------

function makeTestSession(): Session {
  const session = createSession({ output: () => {} })

  // Load clojure.test and refer the test macros into user namespace —
  // same effect as (:require [clojure.test :refer [deftest is testing are]])
  // in a .clj ns form.
  session.evaluate("(require '[clojure.test :refer [deftest is testing are]])")
  session.evaluate('(def __vt_failures (atom []))')

  // :fail — same multiline string as in generateTestModuleCode
  session.evaluate(
    '(defmethod clojure.test/report :fail [m]' +
    '  (swap! __vt_failures conj' +
    '    (str' +
    '      (when (:message m) (str (:message m) "\\n"))' +
    '      "expected: " (pr-str (:expected m)) "\\n"' +
    '      "  actual: " (pr-str (:actual m)))))'
  )
  // :error — captures the actual value (exception or error map)
  session.evaluate(
    '(defmethod clojure.test/report :error [m]' +
    '  (swap! __vt_failures conj (str "error: " (pr-str (:actual m)))))'
  )
  // silence all other report methods (same as generated code)
  session.evaluate('(defmethod clojure.test/report :pass [_] nil)')
  session.evaluate('(defmethod clojure.test/report :begin-test-var [_] nil)')
  session.evaluate('(defmethod clojure.test/report :end-test-var [_] nil)')
  session.evaluate('(defmethod clojure.test/report :begin-test-ns [_] nil)')
  session.evaluate('(defmethod clojure.test/report :end-test-ns [_] nil)')
  session.evaluate('(defmethod clojure.test/report :summary [_] nil)')

  return session
}

/** Run one deftest (by name string) and return the collected failure strings. */
async function runDeftest(session: Session, testName: string): Promise<unknown[]> {
  session.evaluate('(reset! __vt_failures [])')
  await session.evaluateAsync(`(${testName})`)
  const failures = cljToJs(session.evaluate('@__vt_failures'), session)
  return failures as unknown[]
}

// ---------------------------------------------------------------------------
// Async deftest — failure paths
// ---------------------------------------------------------------------------

describe('async deftest — failure paths', () => {
  it('captures a failing is assertion inside (async ...)', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (async (let [x @(promise-of 1)] (is (= x 99)))))')

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(1)
    // is reports (:expected m) as the form, (:actual m) as the evaluated boolean
    expect(failures[0]).toContain('expected: (= x 99)')
    expect(failures[0]).toContain('actual: false')
  })

  it('captures multiple failing assertions from one async deftest', async () => {
    const session = makeTestSession()
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (let [x @(promise-of 1)]' +
      '      (is (= x 10))' +
      '      (is (= x 20))' +
      '      (is (= x 30)))))'
    )

    const failures = await runDeftest(session, 't')

    // All three assertions run even after the first fails (is does not throw)
    expect(failures.length).toBe(3)
  })

  it('leaves __vt_failures empty when all async assertions pass', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (async (let [x @(promise-of 42)] (is (= x 42)))))')

    const failures = await runDeftest(session, 't')

    expect(failures).toEqual([])
  })

  it('propagates a thrown exception from inside (async ...) as a rejected promise', async () => {
    const session = makeTestSession()
    // deftest body throws directly inside the async block
    session.evaluate('(deftest t (async (throw "async-boom")))')
    session.evaluate('(reset! __vt_failures [])')

    // evaluateAsync must reject — the generated async test callback would then
    // propagate the rejection to the test runner (vitest / bun:test).
    await expect(session.evaluateAsync('(t)')).rejects.toThrow()
  })

  it('does not swallow the throw — __vt_failures stays empty when an exception is thrown', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (async (throw "should-not-be-swallowed")))')
    session.evaluate('(reset! __vt_failures [])')

    try {
      await session.evaluateAsync('(t)')
    } catch {
      // expected — swallow here so we can inspect the atom
    }

    // The throw propagated as a rejection, not through the :error report method
    const failures = cljToJs(session.evaluate('@__vt_failures'), session)
    expect(failures).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// Sync deftest — failure paths (regression: ensure async change didn't break sync)
// ---------------------------------------------------------------------------

describe('sync deftest — failure paths', () => {
  it('captures a failing is assertion in a sync deftest', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (is (= 1 99)))')

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(1)
    expect(failures[0]).toContain('expected: (= 1 99)')
    expect(failures[0]).toContain('actual: false')
  })

  it('captures multiple failing assertions from one sync deftest', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (is (= 1 10)) (is (= 2 20)) (is (= 3 30)))')

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(3)
  })

  it('leaves __vt_failures empty when all sync assertions pass', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (is (= 1 1)) (is (string? "ok")))')

    const failures = await runDeftest(session, 't')

    expect(failures).toEqual([])
  })

  it('propagates a thrown exception from a sync deftest as a rejected promise', async () => {
    const session = makeTestSession()
    session.evaluate('(deftest t (throw "sync-boom"))')
    session.evaluate('(reset! __vt_failures [])')

    await expect(session.evaluateAsync('(t)')).rejects.toThrow()
  })
})

// ---------------------------------------------------------------------------
// Mixed — async deftest with testing context
// ---------------------------------------------------------------------------

describe('async deftest — testing context', () => {
  it('captures failures with testing context labels inside (async ...) — lifted @ pattern', async () => {
    const session = makeTestSession()
    // The lifted-@ pattern: deref is in the outer (async let ...), not inside the
    // (testing ...) body. Works before and after the binding-async fix.
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (let [x @(promise-of 1)]' +
      '      (testing "my context"' +
      '        (is (= x 99))))))'
    )

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(1)
    expect(failures[0]).toContain('expected: (= x 99)')
    expect(failures[0]).toContain('actual: false')
  })
})

// ---------------------------------------------------------------------------
// Async deftest — binding inside async
// (binding [...] body) inside (async ...) must run the body
// synchronously — making @deref inside any binding-body fail. That included
// (testing ...) which expands to a (binding [*testing-contexts* ...] (thunk)).
// ---------------------------------------------------------------------------

describe('async deftest — binding inside async', () => {
  it('(binding [...] body) with @deref inside body works', async () => {
    const session = makeTestSession()
    session.evaluate('(def ^:dynamic *factor* 1)')
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (binding [*factor* 10]' +
      '      (let [x @(promise-of 5)]' +
      '        (is (= (* x *factor*) 50))))))'
    )

    const failures = await runDeftest(session, 't')

    expect(failures).toEqual([])
  })

  it('captures a failure from inside (binding [...] @deref-body)', async () => {
    const session = makeTestSession()
    session.evaluate('(def ^:dynamic *factor* 1)')
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (binding [*factor* 10]' +
      '      (let [x @(promise-of 5)]' +
      '        (is (= (* x *factor*) 999))))))'
    )

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(1)
    expect(failures[0]).toContain('actual: false')
  })

  it('binding is popped correctly after async body — var returns to prior value', async () => {
    const session = makeTestSession()
    session.evaluate('(def ^:dynamic *factor* 1)')
    // Run the binding test once to push/pop
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (binding [*factor* 99]' +
      '      (let [_ @(promise-of nil)]' +
      '        (is (= *factor* 99))))))'
    )
    await runDeftest(session, 't')
    // After the test, the binding must have been popped — *factor* should be 1 again
    const val = session.evaluate('*factor*')
    const { cljToJs } = await import('../../core/index')
    expect(cljToJs(val, session)).toBe(1)
  })

  it('(testing "..." (let [x @...] ...)) — @deref inside testing body now works', async () => {
    const session = makeTestSession()
    // testing expands to (with-testing-context* str (fn [] body)), which uses
    // (binding [*testing-contexts* ...] (thunk)). With the binding-async fix,
    // the thunk body runs async, so @deref inside it works directly.
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (testing "inner context"' +
      '      (let [x @(promise-of 42)]' +
      '        (is (= x 42))))))'
    )

    const failures = await runDeftest(session, 't')

    expect(failures).toEqual([])
  })

  it('captures failure from @deref inside (testing ...) body', async () => {
    const session = makeTestSession()
    session.evaluate(
      '(deftest t' +
      '  (async' +
      '    (testing "failing context"' +
      '      (let [x @(promise-of 1)]' +
      '        (is (= x 999))))))'
    )

    const failures = await runDeftest(session, 't')

    expect(failures.length).toBe(1)
    expect(failures[0]).toContain('expected: (= x 999)')
    expect(failures[0]).toContain('actual: false')
  })
})

// ---------------------------------------------------------------------------
// use-fixtures :each — codegen integration
//
// These tests verify that the __vt_each_fixture mechanism produced by
// generateTestModuleCode correctly applies :each fixtures around test calls.
// The session setup mirrors exactly what the codegen emits: after loading
// the test source, `__vt_each_fixture` is defined via join-fixtures, and
// each test invocation calls (__vt_each_fixture (fn [] (test-name))).
// ---------------------------------------------------------------------------

/** Mirror of the fixture setup line emitted by generateTestModuleCode. */
function installEachFixture(session: Session, nsName: string): void {
  const fixtureSetup = `(def __vt_each_fixture (clojure.test/join-fixtures (get @clojure.test/fixture-registry ["${nsName}" :each] [])))`
  session.evaluate(fixtureSetup)
}

/** Run one deftest wrapped by __vt_each_fixture (mirrors generated test() callback). */
async function runDeftestWithFixture(session: Session, testName: string): Promise<unknown[]> {
  session.evaluate('(reset! __vt_failures [])')
  await session.evaluateAsync(`(__vt_each_fixture (fn [] (${testName})))`)
  const failures = cljToJs(session.evaluate('@__vt_failures'), session)
  return failures as unknown[]
}

describe('use-fixtures :each — codegen integration', () => {
  it('applies fixture setup before the test body', async () => {
    const session = makeTestSession()
    session.evaluate(`
      (require '[clojure.test :refer [deftest is use-fixtures]])
      (def log (atom []))
      (defn fx [f] (swap! log conj :setup) (f) (swap! log conj :teardown))
      (use-fixtures :each fx)
      (deftest t (swap! log conj :test))
    `)
    installEachFixture(session, 'user')

    await runDeftestWithFixture(session, 't')

    const log = cljToJs(session.evaluate('@log'), session) as unknown[]
    // cljToJs converts keywords to plain strings (no colon prefix)
    expect(log).toEqual(['setup', 'test', 'teardown'])
  })

  it('applies fixture teardown after the test body', async () => {
    const session = makeTestSession()
    session.evaluate(`
      (require '[clojure.test :refer [deftest is use-fixtures]])
      (def log (atom []))
      (defn fx [f] (f) (swap! log conj :teardown))
      (use-fixtures :each fx)
      (deftest t (swap! log conj :test))
    `)
    installEachFixture(session, 'user')

    await runDeftestWithFixture(session, 't')

    const log = cljToJs(session.evaluate('@log'), session) as unknown[]
    expect(log[log.length - 1]).toBe('teardown')
  })

  it('fixture teardown runs even after a failing assertion', async () => {
    const session = makeTestSession()
    session.evaluate(`
      (require '[clojure.test :refer [deftest is use-fixtures]])
      (def teardown-ran (atom false))
      (defn fx [f] (f) (reset! teardown-ran true))
      (use-fixtures :each fx)
      (deftest t (is (= 1 99)))
    `)
    installEachFixture(session, 'user')

    const failures = await runDeftestWithFixture(session, 't')

    // Failure captured AND teardown ran
    expect(failures.length).toBe(1)
    expect(cljToJs(session.evaluate('@teardown-ran'), session)).toBe(true)
  })

  it('multiple :each fixtures run in correct order (outer→inner setup, inner→outer teardown)', async () => {
    const session = makeTestSession()
    session.evaluate(`
      (require '[clojure.test :refer [deftest is use-fixtures]])
      (def log (atom []))
      (defn f1 [g] (swap! log conj :f1-in) (g) (swap! log conj :f1-out))
      (defn f2 [g] (swap! log conj :f2-in) (g) (swap! log conj :f2-out))
      (use-fixtures :each f1 f2)
      (deftest t (swap! log conj :test))
    `)
    installEachFixture(session, 'user')

    await runDeftestWithFixture(session, 't')

    const log = cljToJs(session.evaluate('@log'), session) as unknown[]
    expect(log).toEqual(['f1-in', 'f2-in', 'test', 'f2-out', 'f1-out'])
  })

  it('fixture side effects are visible inside the test body', async () => {
    const session = makeTestSession()
    session.evaluate(`
      (require '[clojure.test :refer [deftest is use-fixtures]])
      (def state (atom nil))
      (defn fx [f] (reset! state :ready) (f))
      (use-fixtures :each fx)
      (deftest t (is (= @state :ready)))
    `)
    installEachFixture(session, 'user')

    const failures = await runDeftestWithFixture(session, 't')

    // Zero failures → the (is (= @state :ready)) assertion passed
    expect(failures).toEqual([])
  })
})
